# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import reverse_pb2 as reverse__pb2


class messengerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.inMessage = channel.unary_unary(
        '/msgreverse.messenger/inMessage',
        request_serializer=reverse__pb2.input.SerializeToString,
        response_deserializer=reverse__pb2.input_reply.FromString,
        )


class messengerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def inMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_messengerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'inMessage': grpc.unary_unary_rpc_method_handler(
          servicer.inMessage,
          request_deserializer=reverse__pb2.input.FromString,
          response_serializer=reverse__pb2.input_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'msgreverse.messenger', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
