# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reverse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reverse.proto',
  package='msgreverse',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rreverse.proto\x12\nmsgreverse\"\x14\n\x05input\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1d\n\x0binput_reply\x12\x0e\n\x06retMsg\x18\x01 \x01(\t2F\n\tmessenger\x12\x39\n\tinMessage\x12\x11.msgreverse.input\x1a\x17.msgreverse.input_reply\"\x00\x62\x06proto3')
)




_INPUT = _descriptor.Descriptor(
  name='input',
  full_name='msgreverse.input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='msgreverse.input.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=49,
)


_INPUT_REPLY = _descriptor.Descriptor(
  name='input_reply',
  full_name='msgreverse.input_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retMsg', full_name='msgreverse.input_reply.retMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['input'] = _INPUT
DESCRIPTOR.message_types_by_name['input_reply'] = _INPUT_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

input = _reflection.GeneratedProtocolMessageType('input', (_message.Message,), dict(
  DESCRIPTOR = _INPUT,
  __module__ = 'reverse_pb2'
  # @@protoc_insertion_point(class_scope:msgreverse.input)
  ))
_sym_db.RegisterMessage(input)

input_reply = _reflection.GeneratedProtocolMessageType('input_reply', (_message.Message,), dict(
  DESCRIPTOR = _INPUT_REPLY,
  __module__ = 'reverse_pb2'
  # @@protoc_insertion_point(class_scope:msgreverse.input_reply)
  ))
_sym_db.RegisterMessage(input_reply)



_MESSENGER = _descriptor.ServiceDescriptor(
  name='messenger',
  full_name='msgreverse.messenger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=152,
  methods=[
  _descriptor.MethodDescriptor(
    name='inMessage',
    full_name='msgreverse.messenger.inMessage',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_INPUT_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGER)

DESCRIPTOR.services_by_name['messenger'] = _MESSENGER

# @@protoc_insertion_point(module_scope)
